services:
  # Backend API
  - type: web
    name: prontivus-backend
    env: python
    runtime: python
    pythonVersion: "3.11.9"
    region: oregon
    plan: free
    rootDir: .
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: prontivus-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: APP_ENV
        value: production
      - key: DEBUG
        value: false
      - key: CORS_ORIGINS
        value: "https://prontivus-frontend-ten.vercel.app,https://prontivus-frontend-*.vercel.app,http://localhost:5173,http://localhost:3000"
      - key: JWT_ALGORITHM
        value: HS256
      - key: JWT_ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30
      - key: JWT_REFRESH_TOKEN_EXPIRE_DAYS
        value: 30

# Database
databases:
  - name: prontivus-db
    plan: free
    databaseName: prontivus
    user: prontivus

