services:
  # Backend API
  - type: web
    name: prontivus-backend
    env: python
    region: oregon
    plan: free
    rootDir: backend
    pythonVersion: "3.11"
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
      echo "========================================="
      echo "RUNNING DATABASE MIGRATIONS"
      echo "========================================="
      python -m alembic -c app/db/alembic/alembic.ini current
      python -m alembic -c app/db/alembic/alembic.ini upgrade head
      echo "========================================="
      echo "MIGRATIONS COMPLETE"
      echo "========================================="
    startCommand: python start.py
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: prontivus-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: APP_ENV
        value: "production"
      - key: DEBUG
        value: "false"
      - key: CORS_ORIGINS
        value: "https://prontivus-frontend-ten.vercel.app,https://prontivus-frontend-*.vercel.app,http://localhost:8080,http://localhost:5173,http://localhost:3000,http://localhost:8000"
      - key: JWT_ALGORITHM
        value: HS256
      - key: JWT_ACCESS_TOKEN_EXPIRE_MINUTES
        value: 1440
      - key: JWT_REFRESH_TOKEN_EXPIRE_DAYS
        value: 30

# Database
databases:
  - name: prontivus-db
    plan: free
    databaseName: prontivus
    user: prontivus

